[package]
name = "serde_xml"
version = "0.0.1"
authors = ["Oliver Schneider <serde-xml98198@oli-obk.de>"]
license = "MIT non-military non-spy"
description = "xml support for rust-serde"
repository = "https://github.com/oli-obk/serde-xml"

[dependencies.serde]
git = "https://github.com/oli-obk/serde-xml.git"
branch = "xml_requirements"

[dev-dependencies]
serde_macros = "*"
